version: "3.8"

services:
  mongodb:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"

  backend:
    build: ./investment-banking-deal-pipeline-backend
    container_name: backend
    network_mode: host
    # ports:
    #   - "8081:8080"
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/test
  frontend:
    build: ./investment-banking-portal-frontend
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
